- SS_objfunc.tpl
This is an attempted fix for issue #140. I tested locally on the Big Skate model which has lambda = 0 for mean size at age data and the likelihood is now reported (without contributing to the total likelihood).
I also found 4 other locations where adding `save_for_report>0` seemed necessary for consistent reporting, a couple of which already had more complex if() statements.
@Rick-Methot-NOAA, could you check the change in this pull request to confirm that I put the parentheses and || in the right places before merging this change?
> fix: always calculate likelihoods when save_for_report>0 #140

- SS_global.tpl
- SS_write.tpl
This deprecates the SIS_table.sso file (issue #21). For now, the file is still written, but its contents simply have a message referring the user to the r4ss get_SIS_info() function. 
@Rick-Methot-NOAA , let me know if you see any mistakes, or if you think this should be done a different way!
> issue #21 : deprecate SIS table file, with warning

- .github/workflows/run-no-est.yml
This adds a new check on every commit to SS (we can change this frequency if it seems like too much ) where the ss-test-models are run with no estimation and checked if the values are the same or different as in the reference model. Hopefully this will catch changes that impact calculations in the SS code base more quickly.
@Rick-Methot-NOAA , if the checks pass and this description of how this works makes sense to you, please feel free to merge this in! Note it will only be available in main after merging, so if we want to use it in other branches we will need to manually create it (which I can do).
> testing, issue #157 : set up no estimation model runs for each commit

- .github/workflows/build-warnings.yml
- Make_SS_330_new.sh
This addresses #131 . It will warn if there are more warnings than 80, which was the current number of warnings (in the gh_actions_warn branch, at least, not yet sure if the number will need to be adjusted for main) and will create a text file of warning related to SS as an archive. There will probably be some changes we want to make, but I think it can provide value and should be merged into main.
> Add compiler warning gh action to main branch

- SS_objfunc.tpl
- SS_readcontrol_330.tpl
Kelli,
Please check that the se for combined age-length selectivity seems reasonable.  I tried the simple example after increasing N platoons to 5 (just to test the indexing) and I get this:
AgeLenSelex_std_1_GP1_Fem_A_0 0.00529027 0.000715725
AgeLenSelex_std_1_GP1_Fem_A_1 0.0171669 0.00210697
AgeLenSelex_std_1_GP1_Fem_A_2 0.0503977 0.00558243
AgeLenSelex_std_1_GP1_Fem_A_3 0.127717 0.0127583
AgeLenSelex_std_1_GP1_Fem_A_4 0.260027 0.0234945
AgeLenSelex_std_1_GP1_Fem_A_5 0.410182 0.0337065
AgeLenSelex_std_1_GP1_Fem_A_6 0.526735 0.0396442
AgeLenSelex_std_1_GP1_Fem_A_7 0.59982 0.0416719
AgeLenSelex_std_1_GP1_Fem_A_8 0.644169 0.0416408
AgeLenSelex_std_1_GP1_Fem_A_9 0.673059 0.0407983
AgeLenSelex_std_1_GP1_Fem_A_10 0.693696 0.0397205
AgeLenSelex_std_1_GP1_Fem_A_11 0.709521 0.0386378
Thanks, …
> finish fix for combined age-length selex

- .github/workflows/build-centos.yml
- .github/workflows/build-mac.yml
- .github/workflows/build-win-basic.yml
- .github/workflows/build-win.yml
- .gitignore
- SS_versioninfo_330opt.tpl
- SS_versioninfo_330safe.tpl
This PR addresses #202. Now, version info is automatically added based on tags. If a tag with the same commit has been added and has the right format (v3.30.xx.yy, v3.30.xx, or v3.30.xx-prerel), the version as in the tag will be added to the SS version info file before compilation. Otherwise, the last xx version will be used, with .yy = .beta (e.g., a commit after v3.30.17 but before v.3.30.18 and that isn't tagged would be labeled v.3.30.xx.beta).
Note this change does not affect the date of compilation, which will be the true date of compilation due to the use of __DATE__ in the version info.
> build, issue #202: update gh actions build to automate version numbering

- SS_benchfore.tpl
- SS_expval.tpl
- SS_global.tpl
- SS_objfunc.tpl
- SS_popdyn.tpl
- SS_readcontrol_330.tpl
- SS_readdata_330.tpl
- SS_selex.tpl
I noticed some warnings weren't getting incremented, so edited the source code to fix. Note I saw some lines were commented out with no incrementation, but I added it anyway just in case we wanted to uncomment the lines in the future.
@Rick-Methot-NOAA , please take a look. Feel free to push to the branch changes if I made any mistakes, or let me know what changes to make.
> Fix: increment warning where forgotten

- .github/workflows/call-run-ss3-mcmc.yml
- .github/workflows/call-test-r4ss-with-ss3.yml
Adds files to test r4ss with the main branch of ss and for testing that mcmc sampling was working.
These were available on Jenkins, but I am planning on deprecating Jenkins in the not so distant future since we don't run it as often.
> build: add tests for r4ss ss_plots fxn, testing mcmc

- SS_benchfore.tpl
This problem affected forecast of OFL catch in a model with seasons
OFL catch contained only catch from Nseas
Fix involved deleting one line that was re-initializing that quantity
> one line fix for issue #205

- .github/workflows/call-build-ss3-centos.yml
- .github/workflows/call-build-ss3-warnings.yml
- .github/workflows/call-build-ss3.yml
- .github/workflows/call-run-ss3-mcmc.yml
- .github/workflows/call-run-ss3-no-est.yml
- .github/workflows/call-run-ss3-with-est.yml
- .github/workflows/call-test-r4ss-with-ss3.yml
Following https://github.com/nmfs-stock-synthesis/workflows/issues/15 , only build the stock synthesis on changes to the .tpl files. However, the option of manually triggering jobs remains, in case situations come up where builds are desired due to changes in other files.
> Github actions: only build tests on changes to tpl files

- SS_benchfore.tpl
- SS_global.tpl
- SS_objfunc.tpl
- SS_proced.tpl
- SS_readstarter.tpl
- SS_write.tpl
- SS_write_report.tpl
- SS_write_ssnew.tpl
will write to /ssnew and /sso folders if they exist and should write separate report and compreport files in mceval (not tested).
> new_filename_and_folder_for_outputs

- SS_objfunc.tpl
- SS_prelim.tpl
- SS_readcontrol_330.tpl
- SS_tagrecap.tpl
- [#268 and #265  ] Link issue on pull request
retro fix is bandaid only for lencomp superperiod, but  works
fix for tag mirroring needs testing
fix for tag mirroring needs testing
none.  these are minor fixes
> fix for tag mirror #268; partial fix for retro-superperiod #265

- SS_selex.tpl
- SS_write_ssnew.tpl
#228 
This pull requests adds or edits warnings and exit statements for selectivity patterns that have been discontinued or are not recommended.
I compiled and tested out all selectivity patterns that have exits and warnings or just warnings (length patterns 2, 4, 7, 30, 8; age patterns 13, 18).  I did this by modifying the selectivity patterns and number of lines required as in the manual (note pattern says it need 8 parameter lines, but only needs 6)
It would be good for Rick to review the code. In particular, if the single warnings when the model run is not supposed to exit on error are implemented correctly and if there are any changes in wording needed.
Someone checking at least a few of the patterns would be helpful, to make sure my tests also work elsewhere. 
It might be good to …
> Issue 228 - remove and warn unused selex patterns

- SS_objfunc.tpl
Adding mvTweedie likelihood, using `dtweedie` in ADMB-14
- [#277] Link issue on pull request
No tests done!
1. Adding input/output features to get mvTweedie parameters
2. Checking `dtweedie` exists in ADMB
3. Checking likelihood calculation
4. Add code for effective-sample-size calculation somewhere TBD
5. testing on simple example and compare with VAST
to discuss later I think
> Mv tweedie complike

- SS_objfunc.tpl
- SS_readdata_330.tpl
- SS_write_report.tpl
- SS_write_ssnew.tpl
This adds capability to exclude from the tag logL tag groups with less than a specified minimum number of recaptures
- [#280  ] Link issue on pull request
works with the IOTC Yellowfin tuna spatial model
none
input of new feature is conditional on TG_mixperiod having a negative value:
1 # do tags (0/1)
121 # N tag groups
769 # N recap events
-4 # TG_mixperiod (latency) is the first period in which logL is calculated for this tag group (0 = release period)
16 # max periods (seasons) to track recoveries, after which tags are still read into this accumulator period
2 # TG_min_recap:  N recaps >= mixperiod must be >= min_recap to include tag group in logL
@jyqalan
> complete addition of TG_min_recap, and revise compreport

- SS_popdyn.tpl
- SS_proced.tpl
- SS_write_report.tpl
Link issue(s) here: #298 
I tested with the two morphs model (attached), compiled SS3 locally, and ran with no options. The nan message disappeared, however there was a covariance matrix may not be positive definite warning. I'm not sure if this has something to do with the SS3 code, or if it is specific to the model.
[two_morph.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/8563411/two_morph.zip)
If @Rick-Methot-NOAA could take a look and make sure this fix does what I think it does, that would be great!
Add line in the change log about this bug.
> fix, #298: add conditional statement around bmark code

- Compile/exes/echoinput.sso
- SS_write_report.tpl
No space in report:47 between Mat_F_natage and sex_ratio
as reported by @hgerritsen and @iagomosqueira via email.
No issue was filed.
Compiled the fix locally and reran the [input files](https://github.com/flr/ss3om/files/8608982/CheckreadLFSss3.zip)
provided by @hgerritsen.
Old output looked like
```Biology_at_age_in_endyr report:47
in_endyr_with_CV=f(LAA)
Seas Morph Bio_Pattern Sex Settlement Platoon int_Age Real_Age Age_Beg Age_Mid M Len_Beg Len_Mid SD_Beg SD_Mid Wt_Beg Wt_Mid Len_Mat Age_Mat Mat*Fecund Mat_F_wtatage Mat_F_Natage sex_ratio  Len:_1 SelWt:_1 RetWt:_1 Len:_2 SelWt:_2 RetWt:_2 Len:_3 SelWt:_3 RetWt:_3 Len:_4 SelWt:_4 RetWt:_4
1 1 1 1 1 1 0 0 0 0.5 1 2 7.25 0.488 1.769 0.00045239 0.00726627 9.14165e-05 1 0 4.1357e-08 9.14165e-050.5  11.2114 0.0228134 0.0270803 11.0197 …
```
> fix(report:47): Adds space

- SS_write_report.tpl
> Create write comp func

- SS_benchfore.tpl
Link issue(s) here: 
fix to main to repair M in forecast when predators are used.  Note that a separate development branch changes the pred_M2 approach and is not affected by this problem
detailed test using vendance 
none
- [ x] no further changes to r4ss
- [ x] no further changes to the manual
- [x ] no further changes to SSI (the SS3 GUI)
this must get noted in the change log
> fix forecast M with predators

- SS_readcontrol_330.tpl
Link issue(s) here: #321
None, because this change is very simple. Given we use exit(1) elsewhere in the code, it doesn't seem necessary to test this small change.
@Rick-Methot-NOAA to review the change and "approve" it or request edits.
Not sure if this change is worth documenting in the change log? It's really small.
> #321: use exit(1) instead of abort()

- .github/workflows/call-build-ss3-warnings.yml
- SS_global.tpl
- SS_objfunc.tpl
- SS_readcontrol_330.tpl
- SS_readdata_330.tpl
- SS_selex.tpl
- SS_write_report.tpl
- SS_write_ssnew.tpl
Issue was not created, but while working on #123, it became clear to me that some of the warning messages coming from SS3 could be taken care of. This will make it easier to identify new/different warnings in the future using github actions, and also cleans up the codebase a bit. In particular, the changes made are:
- add fallthrough statement to note implicit fallthrough is intentional
- get rid of maybe uninit warning
- use multiline comment instead of single line comment to get rid of warning
- remove parm_adjust_method from create_timevary because unused
- refactor: clean up comments for time varying so only in 1 place (no warning but found while getting rid of parm_adjust_method)
- try to fix warning re using wrong type in for statements
- use int instead of unsigned
- remove unused …
> Fix: remove warnings coming from ss3 source code. Details below

- SS_global.tpl
- SS_readstarter.tpl
> Added write_message and write_warning

- Compile/Make_SS_safe.bat
- SS_benchfore.tpl
- SS_param.tpl
- SS_readdata_330.tpl
- SS_write_ssnew.tpl
Link issue(s) here: #182 
verified with simple example
none, but checking variance would be good idea
> first commit for #182; Bmsy_for_H4010_top

- SS_biofxn.tpl
- SS_readcontrol_330.tpl
- SS_write_ssnew.tpl
This pull request addresses issue #328 to create a survivorship-based Lorenzen M formulation. This formulation facilitates the existing workflow for SEDAR stock assessments. 
This modification has been compiled locally and tested on queen triggerfish and scamp with results matching our externally calculated expectations.  
Google drive link to scamp example (this example didn't have the final pred M refactoring but I did test that locally)
https://drive.google.com/drive/folders/1U6hY1t32pm8AjxP-aZKYVd-DNYZMslcH?usp=sharing
I don't believe this is significantly different than the existing formulation in terms of potential errors.
This change does not impact the current formulation so shouldn't cause errors in existing models.
I will also make a pull request to the doc that takes a first …
> Alt lorenzen

- SS_global.tpl
- SS_readstarter.tpl
> 320 standardize exit message

- Compile/ss.log
- SS_readdata_330.tpl
(note: including the keyword "resolves" means the issue will be closed automatically when merged in.)
Link issue(s), replacing everything in `[ ]`: resolves #[add issue number number], resolves #[optional second issue number if more than 1 issue addressed.]
resolves #330 
N/A
option test; correct warning is created
none
no
```
```
Version | Date       | Description               | Issue        | Input change | Action                | Topic                                     | Type  |
| ----- | ---------- | ---------------------- | ------------ | ------------ | --------------------- | ----------------------------------------- | --------------------------------------- |
3.30.20 | [Add …
> add warning on read of out of range Fcast_relF_Basis

- SS_biofxn.tpl
- SS_param.tpl
- SS_readcontrol_330.tpl
- SS_write_report.tpl
- SS_write_ssnew.tpl
resolves #348 
some aspects of maturity and fecundity were being calculated even in not used; calculated values could be nonsensical if user provided placeholder rather than realistic parameter values.  Solution:  replace output  in these situations with a constant vector of 0.5.  Augment comments in code to describe the relevant situations.
minimal
try it out with the setup identified in issue #348 
no
```
```
r4ss needs to adjust headers for the biology_report (no. 42)
Version | Date       | Description               | Issue        | Input change | Action                | Topic                                     | Type  |
| ----- | ---------- | ---------------------- | ------------ …
> clean up and add comments for mat_fec calcs

- .github/workflows/ss3-pr-open-issues.yml
N/A
This addresses @iantaylor-NOAA 's suggestion to open dependent issues in current or other repositories when creating the pull request, rather than when merging it in. The exact build trigger used will open the issues when the pull request is opened as "ready for review", so draft pull requests will not create issues.
This build trigger has been used in the FIMS workflow https://github.com/NOAA-FIMS/FIMS/blob/main/.github/workflows/pr-checklist.yml , and seems to be working as expected.
Just need to know if others think that opening the issues on creation of the PR instead of merging is better or not.
No
```
```
Version | Date       | Description               | Issue        | Input …
> Change build trigger to be when a PR is opened

- .github/workflows/ss3-pr-open-issues.yml
Refines wording of new messages created in r4ss, doc, or SSI repositories (e.g. https://github.com/nmfs-stock-synthesis/ssi/issues/5).
These issues are now created when a SS3 PR is created, not merged, so changing wording makes things more clear. Plus some additional reformatting may add clarity.
https://github.com/nmfs-stock-synthesis/workflows/issues/43
> revise wording in automatic issue message for other repositories

- SS_selex.tpl
Corrects bug associated with wrong parameter line references in selex pattern 42
resolves #363 
Implemented in attached which runs fine without estimation. Estimation produces nan values but I think that's probably based on bad model design rather than problems with the code.
[BigSkate_splines_selex42_option10.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/9264173/BigSkate_splines_selex42_option10.zip)
Could be useful to add a proper example of selectivity pattern 42 for both length and age.
I'm not totally clear on what this means.
SS3 Manual should clarify that the 2 extra parameters required by pattern 42 come before all of the pattern 27 parameter lines, so the code parameter is now on the 3rd …
> fix: bug in selex pattern 42, fixes #363

- SS_write_report.tpl
The recently-revised (in #307) Natural_Mortality table in Report.sso has an extra value in the output 
This PR replaces #367 which accidentally was based on the `MV-Tweedie-ver2` branch instead of `main`.
No issue. Just a quick fix to a minor bug (example below).
Compiled SS3, ran a single model, confirm that the table looks correct.
Usual automated tests via GitHub action.
Example of the output with the extra "TIME" value in the "BENCH" rows:
```
Natural_Mortality report:43
Method: 0
Area Bio_Pattern Sex BirthSeas Settlement Platoon Morph Yr Seas Time Beg/Mid Era 0 1 2 ...
1 1 1 1 1 1 1 1968 1 1968 B BENCH  TIME  0.1 0.1 0.1 ...
1 1 1 1 1 1 1 1968 2 1968.96 B BENCH  TIME  0.1 0.1 0.1 ...
1 1 1 1 1 1 1 1969 1 1969 B VIRG …
```
> fix extra value in M table (2nd try)

- .github/workflows/call-run-ss3-no-est.yml
- SS_miscfxn.tpl
- SS_objfunc.tpl
- SS_prelim.tpl
- SS_readcontrol_330.tpl
- SS_readcontrol_330.tpl.orig
- SS_readdata_330.tpl
- SS_write.tpl
- SS_write_report.tpl
- SS_write_ssnew.tpl
Reorganizes index logic for comp-weighting parameters in anticipation of the 2-parm MV-Tweedie;
adds information to the Fit_Len_Comp, etc. tables in report.sso, so needs r4ss attention
preps for extending D-M and MV-Tweedie to generalized size comp
still open  #266 
resolves #365  resolves #185 resolves #66  resolves #360 resolves #362 resolves #219 
using Andre_tag as testbed.  Also all_gen_size_comp modified to have a combo of length, age and sizecomp, and a combo of multinomial and Dirichlet-Multinomial (D-M).
r4ss needs updating to read the revised Fit_Len, etc. tables
Yes.
```
-1 # N sizefreq methods to read (or -1 for expanded options)
2 # N sizefreq …
```
> MV tweedie and D-M for sizefreq

- SS_global.tpl
Removes a warning
The call-build-ss3-warnings artifact file should be checked for presence of the implicit fallthrough warning (which should no longer be present):
```
ss.cpp: In function ‘void write_message(int, int)’:
ss.cpp:160:18: warning: this statement may fall through [-Wimplicit-fallthrough=]
160 |         exitflag = 1;
|         ~~~~~~~~~^~~
ss.cpp:161:7: note: here
161 |       case ADJUST:
|       ^~~~
```
@nschindler-noaa , could you check if the fallthrough is intentional, or if this should be `break;` instead?
-[x] I have documented any new code added (or no new code was added)
If so, please provide …
> add fallthrough statement

- .github/ISSUE_TEMPLATE/bug_report.yml
- SS_benchfore.tpl
- SS_global.tpl
- SS_objfunc.tpl
- SS_param.tpl
- SS_popdyn.tpl
- SS_prelim.tpl
- SS_proced.tpl
- SS_readcontrol_330.tpl
- SS_readdata_330.tpl
- SS_readstarter.tpl
- SS_write.tpl
- SS_write_report.tpl
- SS_write_ssnew.tpl
Link issue(s) here: 
#313 . The new ADMB console (#257) inspired me to make some changes to the SS3 console output
Some of the changes have been tested locally by compiling and running a model
When the last changes are made, the output should be looked at in github actions to make sure everything looks ok
May need to check on r4ss and SSI
> Console cleanup

- SS_versioninfo_330opt.tpl
- SS_versioninfo_330safe.tpl
Updates the version number of ADMB to 13.0, using a hard-coded value.
Resolves #373
```
```
> Fixes ADMB version number

- SS_write_report.tpl
- StockSynthesis.code-workspace
reporting of sex ratio in report.sso could produce nan because it was only using area 1 numbers
#378 
#378 
visual examination of biology in endyr report table
none
yes
no
```
```
Inform users that output is now area_specific.  Column header format is now:  sex_ratio_area:X
| [fix, new, or revise] | [e.g., biology. Use …
> 378 bug nan in reportsso for sexratio in hermaphroditism model with second growth morph

- SS_readcontrol_330.tpl
Deleted reports 8, 27, 31, 38, and 42 when reading wtatage.ss.  The message about nobs_mnwt is changed to FATAL (unrelated fix)
Deleting reports that give confusing or unnecessary info when using empirical wt-at-age.
resolves #383.
used Hake_2018 from test_models.
```
```
> disable some reports with use of empirical wtatage

- SS_objfunc.tpl
- SS_readcontrol_330.tpl
- SS_readdata_330.tpl
- SS_readstarter.tpl
- SS_write_ssnew.tpl
successfully add depletion option 5 to use dynamic Bzero as denominator
per request from @SteveTeo-noaa add depletion option 5 that uses dynamic Bzero as the denominator
resolves #69 
created example using simple.  example output attached
[Dyn_Bzero.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/10416386/Dyn_Bzero.zip)
standard
yes
new option is 5
5 # Depletion basis:  denom is: 0=skip; 1=X*SPBvirgin; 2=X*SPBmsy; 3=X*SPB_styr; 4=X*SPB_endyr; 5=X*dyn_Bzero;  values>=11 invoke N multiyr (up to 9!) with 10's digit; >100 invokes log(ratio)
ask me when ready
@jimianelli
> depletion rel dyn_Bzero - working

- SS_global.tpl
- SS_popdyn.tpl
- SS_proced.tpl
- SS_readdata_330.tpl
- SS_readstarter.tpl
- SS_recruit.tpl
- SS_write.tpl
move reset of save_gparm such that mceval does not overflow array bound
resolves issue #397 
resolves #397 
ran example provided by @puntae
none
yes
```
```
> fix array bound error in MCEVAL #397

- SS_readdata_330.tpl
This check on indexing for comperr is too prone to error and misinterpretation.  It is unnecessary, so is removed from code.
resolves #402 
Code now works with the Petrale example linked to the issue
none 
no need.  code was removed
```
```
> remove comperr check rel. Nfleet

- SS_benchfore.tpl
- SS_expval.tpl
- SS_param.tpl
- SS_readcontrol_330.tpl
- SS_readdata_330.tpl
- SS_selex.tpl
- SS_timevaryparm.tpl
- SS_write_ssnew.tpl
- StockSynthesis.code-workspace
enable use of density-dependence with a bounded link env.
add survey type 36 as survey of a recdev
bounded env link was not implemented for density dependence
#165 #41  #390 
#165 #41 
create test using "simple" example.  Temporarily added extra echoinput statements to verify that correct calculations are occurring
@nathanvaughan-NOAA submitted original request, so useful for him to review this
yes
density-dependent env link now works.  It was a  broken option before this code update
```
```
- [ 
clarify that …
> fix #165 for bounded link; add survey type #41

- SS_ALK.tpl
- SS_biofxn.tpl
- SS_expval.tpl
- SS_selex.tpl
The following variables are causing SS3 builds to fail:
ALK_finder
ALK_range_lo
ALK_range_hi
```
```
- [s] no further changes to r4ss
- [s] no further changes to the manual
- [s] no further changes to SSI (the SS3 GUI)
- [s] no further changes to the stock synthesis change log (new features, bug reports)
| [fix, new, or …
> commented out variables

- SS_readcontrol_330.tpl
add warning so dyn_Bzero cannot be selected as depletion denominator unless first selected in extra_std
#69 
#69
warning appears if erroneous setup is used
none
of course
no
```
```
> add dyn_Bzero warning

- SS_benchfore.tpl
- SS_popdyn.tpl
- SS_recruit.tpl
see dialogue with the issue.  The solution was to make SRR_7 robust with a posfun(), just as is done for other SRR
#420 
#420
WIP
fixed output table;
Hessian still notdef so hard-wired beta to value of 0.0 in equil section
```
```
| [fix, new, or revise] | [e.g., biology. Use issue label options.] | [input, output, and/or …
> WIP; correct spawn_recr output; still working Hess

- GNUmakefile
The Make_SS_330_new.sh did not work for me.  So, I create a build file for GNU Makefile developers.
Usage
```
~/stock-synthesis$ make
```
This will build both safe and optimized programs of stock synthesis.
> Add root GNU Makefile

- .github/pull_request_template.md
Simplified the pull request template with redundancies from the issue template (see pr #433) for changes to issue template). Can add those sections back if requested. If you would like to see the example pull request "in action", it is available in a repo of mine [here](https://github.com/e-gugliotti-NOAA/github-actions-test/pull/4).
Major changes to note are: 
1. I removed the doc/r4ss/ssi section. With this change, Issues will not automatically be created in those repos from a pull request or from an issue. It seemed like this feature wasn't working for everyone which is why it was removed, however I'm open to suggestions/putting it back in if people do like that feature. 
2. I removed the section to revise the change log if needed. It didn't look like this feature was being used plus …
> Revised pull request template

- SS_prelim.tpl
- SS_readdata_330.tpl
- SS_write_ssnew.tpl
revision of output when compdata read with 2 as retained, but retention not defined
#437
resolves #437 
eyeball test 
code is not consistent regarding ssnew files.  Data.echo OK, but for other new files need to decide if the original or transformed partition code should be output.  lencomp writes out the revised value of mkt_l(f,i), but agecomp and meansize write out saved value of header_a which is a vector containing the original value of mkt_a, etc.
yes
```
```
| --------------------- | ----------------------------------------- | …
> Fixes #437 regarding partition warning

- SS_readdata_330.tpl
Fcast_MGparm_ave could have years set incorrectly. 
This accepts all year values and sets them according to the manual doc or at least to something that will not cause an error.
year value = -999, <0, <styr, >endyr
[x] No test files are required for this pull request. 
I don't know of any.
[x] No, there was no input change. 
This is an example of the input files (forecast.ss is the affected file).
[simple_averaging-copy.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/11853263/simple_averaging-copy.zip)
This input:
4 1 2001 1066
3 0 10 -4
5 1 2004 2500
1 1 -999 -3
2 1 1066 4
8 0 3000 3000
produced this internal data:
1 1 1971 1998
2 1 1971 1972
3 0 1971 1997
4 1 2000 2001
5 1 2000 2001
0 0 0 0
0 0 0 0
8 0 2000 2001
and these messages in warning.sso
Warning 1 Adjustment: …
> Fcast MGparm averaging year value checks

- SS_global.tpl
- SS_readcontrol_330.tpl
- SS_readdata_330.tpl
Added a Warning: Adjustment when forecast recruitment option is 3 or 4 and end_recruits year is not equal to endyr.
* Resolves issue #471
[x] Test files are in the issue. 
> 471 bug gradient issue with forecast recruitment option 3

- SS_expval.tpl
* Resolves issue #484 
A temporary version of vendance seasonal wtatage model was created and a temporary write statement was put into expval.  This verified that the error existed.  No other usage of Wt_Age_t(y, f) exists in the code.  All are now Wt_Age_t(t, f)
None
> correct index usage in expval

- SS_param.tpl
- SS_prelim.tpl
The checksum value at end of ss.par was intended to provide a check when the number of parameters in the model changed.  This check is now added to ss_prelim.  SS3 will exit if value of checksum, which is not actually a checksum, is not equal to 999.
No issue is linked
No input change for the user.  The 999 value is created when a model is read from the control file.
> repair_check_on_Nparms_in_parfile

- SS_write_ssnew.tpl
* Resolves issue #505 
careful comparison of echoinput and mean_size table for alternative values of recruitment age
none
> modify ssnew text for growth Amax

- SS_benchfore.tpl
format of the MSY search output was corrupted when there is >1 season.  Fix by using colsum to output the sum of catch across seasons for each fleet.
There is no issue.
examined revised output and verified that it was correct to use colsum, not rowsum
[x] No test files are required for this pull request.
> fix MSY search output with >1 season

- SS_write_report.tpl
Fixes bad value reported for size comp method (in Ageerr column of CompReport.sso)
* Resolves issue #539
Running with simple_small_sizecomp model (attached to issue #539) now produces CompReport.sso file with size comp method values that match 3.30.19 output.
No.
> fix size comp method output #539

- .github/workflows/build-ss3.yml
For some reason, the build-artifact workflow is no longer uploading all of the executables from the different operating systems to the same artifact named "ss3" (see artifact from PR #542). I have changed the workflow to upload an artifact for each OS, which is working (see workflow run [here](https://github.com/nmfs-ost/ss3-source-code/actions/runs/7263287295)).
First seen in PR #541 by @iantaylor-NOAA.
None.
> use different artifact names

- .github/workflows/build-ss3.yml
- SS_write_ssnew.tpl
resolves issue #541 
uses code that was created in issue #357  but accidentally deleted
Testing can use this zip, which may be a good candidate for adding to the test repo
[D-M_test.zip](https://github.com/nmfs-ost/ss3-source-code/files/13709772/D-M_test.zip)
Testing demonstrates that data.expval and data.boot1 are different from data_echo.
> restore sizecomp bootstrap output

- .github/workflows/build-ss3.yml
- .github/workflows/run-ss3-mcmc.yml
- .github/workflows/run-ss3-no-est.yml
- .github/workflows/run-ss3-with-est.yml
- .github/workflows/test-r4ss-with-ss3.yml
- SS_global.tpl
- SS_param.tpl
- SS_readstarter.tpl
Resolves issue #319 
ss3.exe -nohess -stopph 3  modelname ss4you
produces expects to read ss4you.par and will write ss4you.par
test with mcmc
No required change.  Provides option to change filename prefix at command line.
This needs to be documented in command line section of the manual
A new command line argument will set the filename for all ADMB output files to "base_modelname.[ext]"
where base_modelname can be read from command line with command: modelname followed by the desired name
e.g.  ss3_win.exe modelname ss4you
When readparfile is used, SS3 will attempt to read ss4you.par.
ss4you will be used as prefix for output files such as ss4you.par and ss4you.cor
if requested modelname.par is not found, then will attempt to …
> allow custom output filenames

- SS_expval.tpl
- SS_objfunc.tpl
- SS_param.tpl
- SS_prelim.tpl
- SS_readcontrol_330.tpl
- SS_readdata_330.tpl
- SS_write.tpl
- SS_write_report.tpl
- SS_write_ssnew.tpl
* Resolves issue #535
<-- - [] Test files are in the issue. -->
needs close look by a math-stat whiz
revision for T-dist
> revise-code-for-catchability-with-bias-correction

- .github/workflows/ss3-pr-open-issues.yml
- SS_write_report.tpl
Resolves issue #556 
visual comparison of values reported in Fit_agecomp table
<- - [x] No test files are required for this pull request. -->
none
< -- [x] No, there was no input change. -->
> fix_lbin_in_FIT_age #556

- SS_readdata_330.tpl
A "nan" likelihood in model shared by @akatan999 took some time to debug (traced to age comp likelihoood, then to rows with zero observations for some bins, then to 0 values for `addtocomp` settings).
It's hard to imagine anyone wanting the `addtocomp` to be zero, so adding a warning when this occurs will make debugging this easier.
Compiled and run on the model that was shared which now produces these warnings:
```
Warning 1 : addtocomp input for age comps fleet 1 is 0 but should be > 0 to avoid log(0) in likelihood
Warning 2 : addtocomp input for age comps fleet 2 is 0 but should be > 0 to avoid log(0) in likelihood
```
Can be replicated on any model by changing `addtocomp` for length or age data to 0 or negative value.
Review by @Rick-Methot-NOAA to confirm that this was done …
> add warning when addtocomp is not > 0

- .github/workflows/build-ss3.yml
- Compile/Make_SS_fast.bat
- Compile/Make_SS_safe.bat
- GNUmakefile
- Make_SS_330_new.sh
> Retry ADMB docker images

- .github/workflows/build-ss3-warnings.yml
- .github/workflows/build-ss3.yml
- .github/workflows/reference_files/warnings_ss_ref.txt
- .github/workflows/run-ss3-bootstrap.yml
- .github/workflows/run-ss3-mcmc.yml
- .github/workflows/run-ss3-no-est.yml
- .github/workflows/run-ss3-with-est.yml
- .github/workflows/test-r4ss-with-ss3.yml
- .gitignore
- .vscode/settings.json
- CONTRIBUTING.md
- Compile/Make_SS_fast.bat
- Compile/Make_SS_safe.bat
- Compile/Make_SS_warn.bat
- GNUmakefile
- Make_SS_330_new.sh
- SS_benchfore.tpl
- SS_objfunc.tpl
- SS_write_report.tpl
- StockSynthesis.code-workspace
- warnings_ss.txt
resolves issue #569 
add output of discard_at_age for forecast years
visual exam of report.sso shows that discard_at-age now appears for forecast years
> Add disc age #569

- SS_global.tpl
- SS_param.tpl
- SS_popdyn.tpl
- SS_prelim.tpl
- SS_proced.tpl
- SS_readcontrol_330.tpl
- SS_readdata_330.tpl
- SS_write_ssnew.tpl
continues development for issue #570  and especially #581
See description and example in #581
Substantial refactoring of the internal machinery for managing F as parameter vs F as hybrid
extends the F-detail approach previously available only for F_method 2 to F_method 4
only new input is for F_method 4 if using the F_detail feature.
> Unify F approach

- SS_readcontrol_330.tpl
Refines echoinput messages and errors associated with read of Q_setup in control file inspired by recent forums post by Laura Lee: https://vlab.noaa.gov/web/stock-synthesis/public-forums/-/message_boards/message/35975358.
* makes more clear which fleet has an issue in Q setup
* aligns notation (now just "Q setup" instead of also "q setup" and "Qsetup")
* adds explanation for why the echoed Q setup table looks different than input
* adds explanation for Q_Npar and Q_Npar2
Files attached to forums messages were used for testing.
Make sure the refinements make sense.
> refine echoinput messages and errors in Q_setup

- SS_readcontrol_330.tpl
This revision to the warning on block endings will resolve issue #579 
none
> #579 update block warning

- .github/workflows/build-admb-and-ss3-from-source.yml
- .github/workflows/build-ss3.yml
- Compile/Make_SS_fast.bat
- Compile/Make_SS_safe.bat
- GNUmakefile
- Make_SS_330_new.sh
The M2 chip macs that use arm64 (including macos-14) seem to behave a bit differently with the ss3 executables than the macs that use x86_64 architecture (macos-12 and before). Building the executable on a macos-14 runner fixed the issue that a user (Juan-Carlos) was having. I have now included building on a macos-14 machine in our GitHub actions. @iantaylor-NOAA noted that the macos-14 built executable does not work on older macs so building macos-12 is also necessary.
**In theory**, the [macos-latest image is supposed to be macos-14 right now](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) BUT a [recent …
> Build macos 14

- SS_readstarter.tpl
- SS_write_ssnew.tpl
Allows for multiyear averaging of F/Fmsy for >10 years.   Per request from @HaikunXu
* Resolves issue #586
example model "simple" was used as test case to demonstrate fidelity of the change.
None
in starter.ss there are needed changes if multiyr or log(ratio) is invoked
> change multiyr average approach

- .github/workflows/build-admb-and-ss3-from-source.yml
- .github/workflows/run-ss3-bootstrap.yml
- .github/workflows/run-ss3-mcmc.yml
- .github/workflows/run-ss3-no-est.yml
- .github/workflows/run-ss3-with-est.yml
- .github/workflows/test-r4ss-with-ss3.yml
- SS_expval.tpl
- SS_readcontrol_330.tpl
- SS_write_report.tpl
- SS_write_ssnew.tpl
* Resolves issue #595 
* is responsive to issue #5
> add offset option for ENV Q

- SS_readcontrol_330.tpl
This PR adds an error when you try to run MCMC with the setting do_recdev = 1. 
It was inspired by this discussion https://github.com/nmfs-ost/ss3-source-code/discussions/566 where a user noted getting bad results in the MCMC which I think are driven by the bug in ADMB described at https://github.com/admb-project/admb/issues/107.
I thought of adding a warning instead of an error, but users may look at the warning file while running MLE estimates, decide that they can ignore the warnings, and not see that a new warning appears when running MCMC. I think the results of the MCMC are incorrect if using recdev option 1 so it's probably better to not allow them to get calculated in the first place.
I ran a model using `ss3 -mcmc 100` and confirmed that the command line and warning file includes …
> add fatal error when using MCMC with recdev option 1

- .gitignore
- Compile/Make_SS_warn.bat
- SS_expval.tpl
- SS_readcontrol_330.tpl
resolves #600 and updates fix for #590 
no additional testing need.  verified syntax of the updated label by viewing output in warning.sso:
Warning 6 : negative discard occurred for fleet: 1; obs: 28; usually ephemeral issue with bad iteration
> update discard warning plus one

- SS_prelim.tpl
- SS_readdata_330.tpl
- SS_write_ssnew.tpl
Initially posting as a draft pull request to foster discussion before marking ready for review.
- Aligns a few inconsistencies in the column headers written to data_echo.ss_new (and expected and boostrap data files).
- more consistent use of lowercase headers
- "season" to "seas" (which is more common)
- "partition" to "part"  (which is more common)
- "SampleSize" to "Nsamp" (which is more common)
- make things match better across the three types of data ss_new files as well as echoinput (in part because this helped confirm that the changes above were made throughout)
- Change "yr" to "year" as suggested in this comment and the one below from @kellijohnson-NOAA https://github.com/r4ss/r4ss/issues/512#issuecomment-1438728972.
- Changes are in parallel with changes in the r4ss function to …
> make column headings more consistent in data files 

- .github/workflows/test-r4ss-with-ss3.yml
- SS_benchfore.tpl
- SS_param.tpl
- SS_popdyn.tpl
- SS_proced.tpl
- SS_readstarter.tpl
- SS_write_report.tpl
resolves #607 
Information is in the issue.
The annual_time_series table has been separated from the SPR_series table such that only per-recruit values are in the SPR table.  
update and check the mean age values
add more notes on each table
Testing can be done with any model.
needs work with r4ss
> separate annual timeseries from spr series; improve mean_age reporting

- .github/workflows/test-r4ss-with-ss3.yml
- SS_write_report.tpl
revise recruitment distribution output to show males and females.  This is helpful for hermaphroditism applications
* Resolves issue #611 
see test file linked in the issue.
revised output is visible in the issue and shows the desired feature
> revise recr_dist output to show both sexes

- SS_objfunc.tpl
- SS_readcontrol_330.tpl
- SS_selex.tpl
Find that the rho feature of 2DAR was incompletely implemented and a full fix is not feasible at this time.  Provide new warnings and guidance to users.
* Resolves issue #615 
Numerous runs with various permutations of estimating or fixing age-specific sigmasel values using hake 2DAR example.
none
> adjust warnings for 2DAR

- SS_global.tpl
Hi, I'm running an SS3 model and notice that the warning.sso output file says "Number of lamdas !=0.0 and !=1.0:  8".
This pull request changes the warning message to say "lambdas" instead of "lamdas".
> Fix typo in warning.sso output file

- .github/workflows/build-ss3.yml
Per the usual, mac is always the problem child. While the macos-latest exe was building using the admb docker image, it wasn't actually working which wasn't detectable until r4ss r_cmd_check() tests ran on macos-latest. Using the build from source workflow, I created a ss3_osx_arm64 exe that works, so I have modified our ss3-build workflow to build both versions of mac from source.
In the future, I think  running the test models with macos latest in addition to it running on linux would be useful, especially since no one has a M2 chip and beyond mac to test on anymore (my mac is old). It would increase the run time but it would ensure that we aren't finding out that it doesn't work later than we want. I'm happy to work on this if you agree. I can even add it as a part of this PR. It won't …
> Build macos-latest admb from source

- SS_readcontrol_330.tpl
- SS_write_ssnew.tpl
Information on use of F_detail needed improvement for F method 4.
no linked issue
The revised control.ss_new now looks like:
```
4 # F_Method:  1=Pope midseason rate; 2=F as parameter; 3=F as hybrid; 4=fleet-specific parm/hybrid (#4 is superset of #2 and #3 and is recommended)
2.95 # max F (methods 2-4) or harvest fraction (method 1)
1 0.05 99 # FISHERY
-9998 1 1 # end of list, triggers reading F_detail
4 #_number of loops for hybrid tuning; 4 precise; 3 faster; 2 enough if switching to parms is enabled
#fleet year seas F_value catch_se phase
1 2000 1 0.05 0.01 1
1 1999 1 0.04 0.01 1
-9999 1 1 1 1 1  # end of F_detail
#
```
and the info in echoinput is:
```
4 F_Method as read
2.95 max_harvest_rate 
read list of fleet ID, starting F, and phase to transition to parameters …
```
> improve Fdetail info in ssnew for Fmethod 4

- SS_write_report.tpl
fixes output error in Index_2 that was introduced with Qtype 6.
* Resolves issue #646 
[x] Test files are in the issue. 
None
> issue 646 - fix output error in Index_2, plus two minor output tweaks

- SS_benchfore.tpl
- SS_prelim.tpl
- SS_readcontrol_330.tpl
* Resolves issue #654 
I created situations with an empirical wtatage model that successfully invoked the two new warnings
None
> 654 apply first mature age

- SS_readcontrol_330.tpl
no Issue created.  Simple revision of language to clarify how retention functions work with EWAA,  New NOTE msg states that when using EWAA, the same body wt is used for discarded and retained fish for both length-retention and age-retention.  i.e.
```
if (seltype(f, 2) >= 1)
{
if (WTage_rd > 0)
{
warnstream << "Length-based retention will use the same empirical wtatage for discard and retained fish for fleet: " << f;
write_message (NOTE, 0);
```
none needed
none
> revise warn msg for retention with EWAA

- .github/workflows/run-ss3-bootstrap.yml
- .github/workflows/test-r4ss-with-ss3.yml
- SS_benchfore.tpl
- SS_selex.tpl
- SS_write_report.tpl
Implements a tested update of the mirroring of age-discard parameters
* Resolves issue #676 
files provided by @chantelwetzel-noaa 
close examination of output by reviewer
> first commit for mirroring age retention

- .github/workflows/run-ss3-no-est.yml
- .github/workflows/run-ss3-with-est.yml
- .github/workflows/test-r4ss-with-ss3.yml
- .gitignore
- Compile/Make_SS_warn.bat
- SS_benchfore.tpl
- SS_global.tpl
- SS_objfunc.tpl
- SS_param.tpl
- SS_popdyn.tpl
- SS_prelim.tpl
- SS_proced.tpl
- SS_readcontrol_330.tpl
- SS_readdata_330.tpl
- SS_readstarter.tpl
- SS_recruit.tpl
- SS_timevaryparm.tpl
- SS_write.tpl
- SS_write_report.tpl
- SS_write_ssnew.tpl
- StockSynthesis.code-workspace
continuation of PR #442 after updating from 3.30.23 main on 11/06/2024
This implements SRR function 10 for Bev-Holt with alpha, beta
also adds two new controls to give user more control of how time-varying biology affects benchmark and control rule implementation.
Resolves issue #191, #341, #625
See the checkboxes at top of issue #191 for the list of major changes with this branch.
> 191 spawner recruit rebased

- SS_benchfore.tpl
The join function creating differentiable values for the piecewise-linear harvest control rule was leading to OFL*buffer != ACL, with differences in projected catch limits of 1-2 tons. 
Catch limits are the subject of lots of interest, it's important to have the calculations match exactly. This may only impact petrale sole where the projection was occurring very close to the break point in the HCR. I worked around the problem previously by using fixed catches in the forecast file, but a new catch-only projection would benefit from this change to SS3.
Resolves issue #485
I tested replacing the multiplier 10 in the join function with 100 and 1000. Both produced identical results with OFL*buffer == ACL (identical within the accuracy of the precision of the reported values). Therefore, this …
> Apply a steeper join function for the piecewise-linear harvest control rule

- SS_readcontrol_330.tpl
See the issue for description of error in timing of time offset between spawning and settlement for certain model configurations
@alexjensen-NOAA
* Resolves issue #691 regarding the timing between spawning and settlement when settlement is at age > 0
* clarifies that recdev year refers to the year in which the recruitment was spawned
@alexjensen-NOAA
close comparison of results as documented in the issue.
> change settle_seas_offset to work when settlement age is not 0

- SS_write_report.tpl
provide added output to enable adjustment of mean recruitment.
* Resolves issue #594 
<-- - [x] Test files are in the issue. -->
testing with hake_2018
> add mean recruitment output to spawn_recr table

- SS_benchfore.tpl
- SS_popdyn.tpl
* Resolves issue #700 to correct a problem introduced with 
to correct a problem introduced with #691 
@CaitlinAkselrud-NOAA
detailed examination of natage tables using the two season sardine example that has spawning at beginning of season 2 and recruitment at age 0 at the beginning of the following year.
> remove unneeded natatage()=0

- .github/workflows/build-admb-and-ss3-from-source.yml
- .github/workflows/build-ss3.yml
- .github/workflows/run-ss3-with-est.yml
- .github/workflows/test-simple-with-ss3-artifacts.yml
- The build-admb-and-ss3-from-source workflow runs weekly. This action failed for the macos-13 runner and needed to add qpdf in order to get it to pass
- The workflow to test build-ss3 with the simple model on all operating systems started failing 3 weeks ago and I have no idea why. A shortcoming of github actions is to try to even troubleshoot and fix bugs, they have to be on the main branch when using the `workflow-dispatch` trigger which means this might be one of many PRs trying to resolve the issue with this action failing.
None.
> Try fixing test simple model with artifacts; add qpdf to build admb and ss3 from source workflow

- SS_write_report.tpl
simple addition to reduce null tables
* Resolves issue #702 
None
> use use_morph(g) in more output tables

- SS_param.tpl
- SS_selex.tpl
- SS_write_report.tpl
* Resolves issue #717
Description of the change is in the issue
Be sure that r4ss is happy
> augment F reporting
