SS_global.tpl, SS_prelim.tpl, SS_readcontrol_330.tpl, SS_readstarter.tpl
A few changes lingering from issue #109 
- change pick_report_use(54) to pick_report_use(60) for wtatage.ss_new
- add WTage_rd to echoinput
- fix a filter for values outside the 1-60 range for custom report choices
All this allows the custom report option to work for wtatage.ss_new if requested.
=> small changes related to wtatage.ss_new

SS_biofxn.tpl, SS_popdyn.tpl, SS_write.tpl, SS_write_report.tpl
test ready for improvements to totbio and smrybio reporting
=> Issue#154 smrybio

SS_global.tpl, SS_popdyn.tpl, SS_write_report.tpl
the logic for creating this report is fixed with this commit.  Check it out.
=> fixing issue #158  spr/ypr report

SS_benchfore.tpl, SS_biofxn.tpl, SS_global.tpl, SS_popdyn.tpl, SS_prelim.tpl, SS_readcontrol_324.tpl, SS_readcontrol_330.tpl, SS_timevaryparm.tpl, SS_versioninfo_330opt.tpl, SS_versioninfo_330safe.tpl, SS_versioninfo_330trans.tpl, SS_write_report.tpl, SS_write_ssnew.tpl
ready to see if re-arrangements needed for Maunder M (new natmort option=5) have broken anything else.
=> Natmort again

SS_ALK.tpl, SS_benchfore.tpl, SS_biofxn.tpl, SS_popdyn.tpl, SS_write_report.tpl
tested with big_skate and with simple models.  Variance of SSB_unfished now matches variance of SSB_virgin as it should in these examples.  Ready for testing.
=> This fix addresses discrepancies in variance of SSB_unfished

SS_benchfore.tpl, SS_objfunc.tpl, SS_param.tpl, SS_readcontrol_324.tpl, SS_readcontrol_330.tpl, SS_readstarter.tpl, SS_write.tpl, SS_write_ssnew.tpl
=> include fix to parsing of F_std_basis

SS_readcontrol_330.tpl, SS_readdata_330.tpl, SS_versioninfo_330opt.tpl, SS_versioninfo_330safe.tpl, SS_versioninfo_330trans.tpl, SS_write_ssnew.tpl
limit is now removed and the label for D-M parameters is changed.  see issue #183
=> fix for erroroneous limit on D-M parameters

SS_biofxn.tpl, SS_readcontrol_330.tpl
change should only affect Lorenzen M models that use seasons
=> fix lorenzen M for seasons

.github/workflows/build-warnings.yml, SS_benchfore.tpl, SS_global.tpl, SS_param.tpl, SS_readcontrol_330.tpl, SS_readdata_330.tpl, SS_versioninfo_330safe.tpl, SS_write_report.tpl, SS_write_ssnew.tpl
This augmentation will provide output of the equilibrium F associated with Blimit.  See issue #188
=> Search f blimit

SS_global.tpl, SS_objfunc.tpl, SS_readcontrol_330.tpl, SS_readstarter.tpl, SS_versioninfo_330opt.tpl, SS_versioninfo_330safe.tpl, SS_write.tpl, SS_write_report.tpl, SS_write_ssnew.tpl
simple.  should affect only header info in output files.
=> Feature#201 versioninfo

SS_benchfore.tpl, SS_param.tpl, SS_popdyn.tpl, SS_readdata_330.tpl, SS_readstarter.tpl, SS_write_report.tpl, SS_write_ssnew.tpl
=> Andre bioecon

SS_biofxn.tpl, SS_popdyn.tpl
quick fix to improve implementation of predator M2
linked to issue #45
=> improve_predator_M2

SS_param.tpl, SS_readcontrol_330.tpl, SS_write_ssnew.tpl
=> implement revision of F_Method 4 to allow constant F

SS_benchfore.tpl
complete the fix in forecast to updating empirical wtatage
see issue #136
=> complete fix to wtatage  #136

SS_write.tpl
=> rm extra empty line from control file

SS_readcontrol_330.tpl, SS_selex.tpl
New pull request related to #86. I had some issues with linebreaks creating the appearance of all lines changed in the SS_selex.tpl file, so I transferred the changes to a new `spline_issue_86` branch and confirmed that it compiles and operates the same as the messed up `spline_issue_82789` branch (named after original issue number in VLab).
=> option for age 0 selectivity below first spline knot (in new branch) #86

SS_popdyn.tpl
changes #255, #246 
Ran a hermaphroditic model (gag) from the main branch and found a bunch of warnings generated. Not possible to upload model files.
The warning file: 
[warning_sso.txt](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/8043708/warning_sso.txt)
@Rick-Methot-NOAA check that this should indeed be removed
n/a
n/a
=> rm line inserted during debugging

SS_benchfore.tpl, SS_biofxn.tpl, SS_global.tpl, SS_proced.tpl
working with hake_2021 input files that were saving report file for each mceval.
problem was the result of an interation between:  use of empirical wtatage, doing report.sso for each mceval, and changes in wtatage storage initiated during development of 3.30.19.
@kellijohnson-NOAA  should take a look
this is internal calculation only.  No other changes needed
none
=> Streamline ss proced

SS_readdata_330.tpl, SS_write.tpl, SS_write_ssnew.tpl
Additional lines for West Coast rebuilder
=> Issue 232 added lines to rebuild.dat

SS_readcontrol_330.tpl
- [#271  ] Link issue on pull request
tested by requesting this feature using simple
none
none
=> fix calc of N elements for covar

SS_global.tpl, SS_objfunc.tpl, SS_readdata_330.tpl, SS_write.tpl, SS_write_ssnew.tpl
=> Change to make rebuilder option 0/1 (off/on)

.github/pull_request_template.md
Changes the PR template checklist so checked boxes mean a complete rather than incomplete task. 
Status-quo template makes it look like 4 checked boxes doesn't require more work.
=> refine pull request template

.github/workflows/call-build-ss3.yml, .github/workflows/call-run-ss3-no-est.yml, .github/workflows/call-run-ss3-with-est.yml
This reduces the number of github action runs done, as there were redundant runs.
Link issue(s) here: https://github.com/nmfs-stock-synthesis/workflows/issues/32
n/a
Check that the gha builds are passing (edit: none were triggered, as there are no changes to the ss3 codebase). and a quick review that the code changes make sense.
=> reduce redundant gha checks

SS_popdyn.tpl
Link issue(s) here:  #288 
checked it out using simple example after diagnosing with some testing outputs
none
- [X ] no further changes to r4ss
- [X ] no further changes to the manual
- [X ] no further changes to SSI (the SS3 GUI)
This should be reported in the change log
This should be reported in the change log.
report.sso catch_at_age was erroneously reporting available numbers, not catch numbers.
=> fix reporting of catage in equilibrium and initial year report

SS_ALK.tpl, SS_benchfore.tpl, SS_biofxn.tpl, SS_expval.tpl, SS_global.tpl, SS_miscfxn.tpl, SS_objfunc.tpl, SS_popdyn.tpl, SS_prelim.tpl, SS_proced.tpl, SS_recruit.tpl, SS_selex.tpl, SS_tagrecap.tpl, SS_timevaryparm.tpl, SS_versioninfo_330opt.tpl, SS_versioninfo_330safe.tpl, SS_write.tpl, SS_write_report.tpl, SS_write_ssnew.tpl
updating to make all code consistent.
Link issue(s) here:
=> 163 - some whitespace changes

.github/workflows/call-build-ss3.yml, CONTRIBUTING.md, Make_SS_330_new.sh
Link issue(s) here: 
#314, #315
=> Linux build

SS_param.tpl, SS_popdyn.tpl, SS_write_report.tpl
Link issue(s) here: 
none
visual exam using vendance model
the gha will be sufficient
- [ x] no further changes to r4ss
- [ x] no further changes to the manual
- [x ] no further changes to SSI (the SS3 GUI)
- [x ] no further changes to the stock synthesis change log (new features, bug reports)
none
This change fills in blanks for pred_M2 and associated catch for the virgin and initial equilibrium years
=> add reporting for virg and inityr for predators

SS_global.tpl, SS_readdata_330.tpl
updated SS_readdata_330 warning messages and coding style.
updated write_message and write_warning to pass warning number.
updated SS_global warning messages.
(note: including the keyword "resolves" means the issue will be closed automatically when merged in.)
Link issue(s), replacing everything in `[ ]`: resolves #[add issue number number], resolves #[optional second issue number if more than 1 issue addressed.]
Version | Date       | Description               | Issue        | Input change | Action                | Topic                                     | Type  |
| ----- | ---------- | ---------------------- | ------------ | ------------ | --------------------- | ----------------------------------------- | --------------------------------------- |
3.30.20 | [Add date] | [add concise …
=> updated SS_readdata_330

.clang-format, SS_param.tpl, SS_readcontrol_330.tpl, SS_readdata_330.tpl, SS_readstarter.tpl
clang format is now applied to readdata and readcontrol and other files previously left off the style application.  They can now be included because of ability to turn clang-format on/off within the code itself.
GHA is enough
Version | Date       | Description               | Issue        | Input change | Action                | Topic                                     | Type  |
| ----- | ---------- | ---------------------- | ------------ | ------------ | --------------------- | ----------------------------------------- | --------------------------------------- |
3.30.20 | [Add date] | [add concise description] | #[add issue] | [yes or no]  | [fix, new, or revise] | [e.g., biology. Use issue label options.] | [input, output, and/or calc, or ALL] |
=> 163 new style

.github/workflows/ss3-pr-open-issues.yml
partially addresses https://github.com/nmfs-stock-synthesis/workflows/issues/43
This creates a github action that will look at the check boxes in the pull request template and if r4ss, ssi, or the manual require changes, open an issue. The issue looks like this currently:
Title: `Changes need for SS3 PR 45 `
Body: 
```
Changes are needed due to the merging of SS3
PR #45. Please see
https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/45
and its associated issues for more information.
```
I tested this out in a sandbox repository, and tried checking off different combinations of options to make sure that the github action worked appropriately. I also did one test to make sure the github action can post to the r4ss, ssi, and doc repos.d
I have not tested with the text from the …
=> init github action to open issues on pr merging

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/ss3-release-template.md
Creates issue templates for ss3. Includes templates for users (bug report and feature request) and the ss3 dev team (release checklist template, @kellijohnson-NOAA 's suggestion)
N/A
We will have to see if these work as expected once merging into main
@Rick-Methot-NOAA should review the text and make any edits re wording.
```
```
| [fix, new, or revise] | [e.g., biology. Use issue label options.] | [input, output, and/or calc, or …
=> init: issue templates for ss3

.github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/refactor_request.yml
Rewords the feature request issue template and adds a refactor template.
Fixes issues identified by Rick Methot in PR #353 (the PR was merged in before these were corrected)
N/A
@Rick-Methot-NOAA to review the changed text and initial refactor template.
```
```
=> Edit issue templates

.github/workflows/call-build-ss3-warnings.yml, .github/workflows/call-build-ss3.yml, .github/workflows/call-run-ss3-mcmc.yml, .github/workflows/call-run-ss3-no-est.yml, .github/workflows/call-run-ss3-with-est.yml, .github/workflows/call-test-r4ss-with-ss3.yml, .github/workflows/ss3-pr-open-issues.yml
(note: including the keyword "resolves" means the issue will be closed automatically when merged in.)
Addresses a request by @Rick-Methot-NOAA to reduce the number of unnecessary runs of gha workflows as much as possible. I found that 2 workflows (running models with estimation, and running models without estimation) could be reduced, by only having them run on the main branch and every pull request to main, rather than running on every push to every branch.
I also made sure workflows had a `workflow_dispatch:` build trigger, which means there is an option to run the workflow manually using a button under the "Actions" tab. 
Finally, I added a one line comment about what each workflow does in the github action workflows.
None, if the github actions pass on this PR, it should be ok to …
=> Gha build triggers: reduce runs and standardize syntax

SS_benchfore.tpl
get_NatMort() needs to be called if predators are used
none
none
no need, tests had already occurred in old stale branch
none
```
```
none
none
=> Update get_Natmort in SS_benchfore.tpl to happen with predators

SS_ALK.tpl, SS_biofxn.tpl, SS_expval.tpl, SS_readcontrol_330.tpl, SS_readstarter.tpl, SS_selex.tpl
=> 342 deprecate alk tolerance

SS_global.tpl, SS_objfunc.tpl, SS_prelim.tpl, SS_readcontrol_330.tpl, SS_readdata_330.tpl, SS_write_report.tpl, SS_write_ssnew.tpl, StockSynthesis.code-workspace
This change allows for the D-M parameters to be partition specific.
#93 
incremental progress here
test input files attached.  Two dummy observations added that use different D-M parameter
yes
conditional input change invoked by the use_lengthcomp flag
conditional input change invoked by the use_lengthcomp flag
```
2 # use length composition data (0/1/2) where 2 invokes new comp_comtrol format
#_fleet partition mintailcomp addtocomp combM+F CompressBins CompError ParmSelect minsamplesize
0 0 0.0001 4e-07 0 0 0 0 1
1 1 0.0001 2e-07 0 0 1 1 1
1 2 0.0001 …
```
=> 93 allow separate data weighting by partition

.gitignore, SS_readdata_330.tpl, StockSynthesis.code-workspace
simple spellcheck.  Also removing Rick's VSCode settings from git
=> spell check

SS_versioninfo_330opt.tpl, SS_versioninfo_330safe.tpl
Update the admb version from 13.0 to 13.1
#392 
```
```
=> update to admb 13.1 in version files

SS_ALK.tpl, SS_global.tpl, SS_param.tpl, SS_readcontrol_330.tpl, SS_write_report.tpl, SS_write_ssnew.tpl
Changes sd_ratio from value to parameter. Adds a parameter to the MG params.
resolves #325
[test_platoon_varparm.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/10829744/test_platoon_varparm.zip)
none needed.
Yes.
Modifications made to readcontrol such that an additional MGparm line is read if sd_ratio is < 0.
In ALK, the key change is:
if (sd_ratio_rd < 0)   {
dvar_platoon_ratio = MGparm(sd_ratio_param_ptr);
in the control file,
```
5 #_N_platoons_Within_GrowthPattern 
-1.09227 #_Platoon_within/between_stdev_ratio (no read if N_platoons=1)
#_Cond sd_ratio_rd < 0: platoon_sd_ratio parameter required after movement params.
0.031 0.237 0.464 …
```
=> 325 make platoon variance ratio a parameter

.github/ISSUE_TEMPLATE/ss3-release-template.md
=> Update release checklist with item to check ADMB warnings

SS_objfunc.tpl, SS_param.tpl, SS_popdyn.tpl, SS_readdata_330.tpl, SS_write_ssnew.tpl
init_equ_catch logL was accessing incorrect season for the catch_se
#412 
#412 
none
yes
no
```
```
=> first commit; working; some commented out code

CONTRIBUTING.md
Add detail about using GNUmakefile to Contributing.md
Linked to pr #422
```
```
=> Update Contributing.md - using GNUmakefile

.github/ISSUE_TEMPLATE/new_issue_template.yml
@Rick-Methot-NOAA suggested removing checkboxes in PR #434 because it makes it look like there are still things to do so I converted these to dropdown options instead. Please go to [this link](https://github.com/e-gugliotti-NOAA/github-actions-test/issues/new/choose) click on "Get Started" to see the changes live in my own Github repository.
- [ X ] no further changes to r4ss
- [ X ] no further changes to the manual
- [ X ] no further changes to SSI (the SS3 GUI)
- [ X ] no further changes to the stock synthesis change log (new features, bug reports)
=> Update new_issue_template.yml with dropdown boxes

SS_write_report.tpl
obs with sex=0 were being written twice. Fixed here.
issue #435 
resolves #435
eyeball test
none
not needed
```
```
- [x ] no further changes to r4ss
- [x ] no further changes to the manual
- [x ] no further changes to SSI (the SS3 GUI)
- [x ] no further changes to the stock synthesis change log (new features, bug reports)
=> fix_compreport_for_sex0

SS_readcontrol_330.tpl
* Resolves issue #469
verify that use of 99 as fleet does not trigger irrelevant warning.
none
=> Fix bug in lambda warnings and update echoinput for lambda

SS_expval.tpl, SS_readcontrol_330.tpl, SS_readdata_330.tpl
see info with the issue
* Resolves issue #466
temporary edits to simple example were used to test display of the new warnings
[recr_svy_test.zip](https://github.com/nmfs-stock-synthesis/stock-synthesis/files/12017818/recr_svy_test.zip)
=> implement changes and warnings for recr surveys

SS_readcontrol_330.tpl, SS_write_ssnew.tpl
minor changes to text associated with setup of 2DAR selectivity
none
=> minor text updates

SS_readcontrol_330.tpl
An adjustment warning was added for checking/adjusting the end year to MaxYr.
All adjustments moved to before other checks for problems.
Resolves issue #478
The dogfish example was used to test.
[x] Test files are in the issue. 
If no additional tests are needed, please put None.
=> issue  478 add warning if a time block is set to end in endyr

.github/pull_request_template.md, .github/workflows/email_when_close_pr.yml
Add a GitHub action to send an email to the person that created a PR when that PR is closed **if there is a linked issue**. This email is to remind the person to move any pertinent information from the PR back to the issue(s). (Unfortunately, after many attempts, I could not actually include the link to the issue or PR). This is just an option and if others think it is unnecessary then of course I can delete the pull request. Would love to hear what others think of this.
None.
Image of example email that you would receive:
=> Add workflow send email when close pr

SS_readdata_330.tpl, SS_recruit.tpl, SS_write_ssnew.tpl
* Resolves issue #487 
used any forecast.ss file, set forecast recruitment control(3) to value of 4, set multiplier to 10. Saw that output recruitments in forecast were 10*recent average
< [x] No test files are required for this pull request. -->
None
revisionof existing option.  Is labelled in forecast.ss_new and in echoinput.sso
=> revised fore_control 4 to use multiplier

SS_objfunc.tpl, SS_param.tpl, SS_readdata_330.tpl
Bring in Cole's forked branch to a new branch in the stock-synthesis repo. 
None.
=> Add generalized gamma index

.github/workflows/build-ss3-warnings.yml, .github/workflows/build-ss3.yml, .github/workflows/run-ss3-mcmc.yml, .github/workflows/run-ss3-no-est.yml, .github/workflows/run-ss3-with-est.yml, .github/workflows/ss3-pr-open-issues.yml, .github/workflows/test-r4ss-with-ss3.yml
Using another PR to ensure that the action works correctly on opening a PR. Change workflows to not run on draft PR except for the build-ss3 and the run-ss3-no-est which should run on every push per request of Rick.
Issue seen in PR #494 
None.
=> Fix pr open issues workflow

SS_benchfore.tpl, SS_global.tpl, SS_readcontrol_330.tpl, SS_readdata_330.tpl, SS_recruit.tpl, SS_selex.tpl, SS_write_report.tpl, SS_write_ssnew.tpl
* Resolves issue #493 
passing the GHA tests.
also did character-level compare of report, echoinput and forecast-report to identify any differences.  All are related to intended changes in text; no meaningful diffs in numeric values.  This test is what facilitated the fix for vermillion.
[x] The input change is in the related issue(s). -->
=> new fcast year approach

.github/workflows/run-ss3-mcmc.yml, .github/workflows/run-ss3-with-est.yml, .github/workflows/ss3-pr-open-issues.yml, .github/workflows/test-r4ss-with-ss3.yml
Fixing PR trigger to run actions also when PR moves from draft to ready for review
None.
=> Fix pr workflows

SS_benchfore.tpl, SS_param.tpl, SS_popdyn.tpl, SS_write_report.tpl, SS_write_ssnew.tpl
addresses issue #499 
eyeball test.  Example output included in issue #499 
None
=> add vuln_bio and max_sel to report

.github/ISSUE_TEMPLATE/ss3-release-template.md
Remove Neal from release checklist. Minor edits to checklist.
None.
=> Update ss3-release-template.md without neal

SS_write_report.tpl
* Resolves issue #502 
reported in issue.  No files needed
=> add mature_bio and mature_num to time_series table

.github/workflows/build-ss3-warnings.yml, SS_write_report.tpl, SS_write_ssnew.tpl
something went wrong in the merging of the add_vuln_bio issue.  Fixing it here.
#499 
#499
=> Update add vuln bio

SS_write.tpl
* Resolves issue #512
attn:  @brianlangseth-NOAA
#What tests have been done? 
none
#Where are the relevant files?
[x] No test files are required for this pull request. 
#What tests/review still need to be done?
none
=> add sexratio to rebuilder

SS_write_ssnew.tpl
Change "gender" to "sex" in all of the data file comments per the suggestion of @chantelwetzel-noaa.
* Resolves issue #516 
None.
=> replace gender with sex in data file comments

README.md
Fix links to user manual tutorials given file name changes to ss3 instead of ss.
* Resolves issue #527
None.
=> update readme with file name changes for doc

.github/ISSUE_TEMPLATE/new_issue_template.yml, .github/ISSUE_TEMPLATE/ss3-release-template.md, .github/workflows/build-ss3.yml, .github/workflows/email_when_close_pr.yml, .github/workflows/run-ss3-mcmc.yml, .github/workflows/run-ss3-no-est.yml, .github/workflows/run-ss3-with-est.yml, .github/workflows/ss3-pr-open-issues.yml, .github/workflows/test-r4ss-with-ss3.yml, CONTRIBUTING.md, README.md, SS_benchfore.tpl, SS_versioninfo_330opt.tpl, SS_versioninfo_330safe.tpl
This is changing all the repo names in preparation for migration to GHEC:
stock-synthesis -> ss3-source-code
doc -> ss3-doc
user-examples -> ss3-user-examples
test-models -> ss3-test-models
None.
You will see pull requests like this across the nmfs-stock-synthesis org and a PR in r4ss.
=> change repo name to ss3-source-code

.github/workflows/run-ss3-no-est.yml, .github/workflows/run-ss3-with-est.yml, .github/workflows/test-r4ss-with-ss3.yml
The following workflows have been parallelized using the {furrr} package:
- run-ss3-with-est
- test-r4ss-with-ss3
- run-ss3-no-est (via the ss3-test-models updated R script run_from_par.R)
See successful workflows on the branch [here](https://github.com/nmfs-ost/ss3-source-code/actions?query=branch%3Aparallel-est-workflow); these were run by changing the workflow trigger to run workflows on all pushes (this was changed back to the original setting for the PR)
None.
=> Parallelize workflows

SS_write_report.tpl, SS_write_ssnew.tpl
Resolves issue #534 
Before this change, the program would exit at or after writing the header info for the first bootstrap file.  This would occur about every 5 runs.  After the change, I encountered no exiting even after >10 runs.
=> #534 repair string error in bootstrap data header

.github/workflows/run-ss3-bootstrap.yml
Add workflow to test bootstrap files. Will need to wait on this until the PR to add Simple_with_DM_sizefreq has gone through in the test models repo.
Local testing plus test workflow with push.
=> Add bootstrap workflow

.devcontainer/devcontainer.json, .devcontainer/install.R
Add devcontainer file to have codespace with R and Rstudio for testing github actions, making changes, etc.
* Resolves issue #548
None.
=> add .devcontainer

.devcontainer/devcontainer.json, README.md
This addition makes sure that you can access docker within the codespace and use docker commands.
This addition makes sure that you can use docker commands.
Tested on the branch to make sure I could use the docker pull command
=> Update devcontainer.json - add docker

.github/workflows/run-ss3-with-est.yml
Quick to to workflow to update par name to new format (ss3.par)
None.
=> Fix reference to par files in est workflow to ss3.par

SS_readcontrol_330.tpl
resolves issue #570 
more complete work on Fmethod will follow in the unify F approach branch
=> 570 simple fix for FM4

.github/workflows/build-admb-and-ss3-from-source.yml, .github/workflows/build-ss3-from-admb-source.yml, .github/workflows/build-ss3-warnings.yml, .github/workflows/build-ss3.yml, .github/workflows/run-ss3-bootstrap.yml, .github/workflows/run-ss3-mcmc.yml, .github/workflows/run-ss3-no-est.yml, .github/workflows/run-ss3-with-est.yml, .github/workflows/test-r4ss-with-ss3.yml
- Adding a github action that that is only triggered manually to build admb and ss3 from source for windows, mac, and linux. This action is a backup for if/when the admb docker images don't work. Building both admb and ss3 from source gives us more control over the g++ libraries too. [Successful GitHub actions run of this workflow](https://github.com/nmfs-ost/ss3-source-code/actions/runs/8457542489).
- For windows, admb is specifically built using the compilers in Rtools 42.
- Also updated the actions/checkout to version 4 for all workflows
None.
=> Build admb and ss3 from source github action

.github/workflows/build-admb-and-ss3-from-source.yml, .github/workflows/build-ss3-warnings.yml, .github/workflows/build-ss3.yml, .github/workflows/run-ss3-bootstrap.yml, .github/workflows/run-ss3-mcmc.yml, .github/workflows/run-ss3-no-est.yml, .github/workflows/run-ss3-with-est.yml, .github/workflows/test-r4ss-with-ss3.yml
- Adds more description/detail to workflows to describe what they do.
* Resolves issue #456 
None.
=> Update workflows to add more detailed descriptions; put condition on run-ss3-with-est

SS_benchfore.tpl
#605 
[x] No test files are required for this pull request. 
None.  Detailed examination of output was sufficient.  zip with excel file is in the issue.
=> fix for forecast seasonal recruitment

README.md
Update a couple links to now go to the ss3-website.
None.
=> Update README.md with links to the ss3-website

README.md
Probably were duplicated when dealing with merge conflicts at some point.
None.
=> Delete duplicate badges in README.md

.github/workflows/add-exe-build-artifacts-to-PR.yml
The same workflow is in the ss3-doc repo. See [this closed PR from the ss3-doc repo](https://github.com/nmfs-ost/ss3-doc/pull/248) to view how the action adds the artifacts to a PR.
* Resolves issue #597. 
None.
=> Add workflow to add comment in PR with artifacts of successful ss3 builds

SS_readdata_330.tpl, SS_write_report.tpl
* Resolves issue #619 
season duration calculation have been compared to season duration for a survey with same timing.  They did not match before, now they do.
Test file is in email with nmfs.stock.synthesis
None
=> revise calc of spawn_time_season

SS_readdata_330.tpl
simple increase in storage of have_data array to allow more CAAL observations.  New limit is 150.
* Resolves issue #622 
revised sablefish model runs with this increased storage
none
[x] No, there was no input change. -->
```
If there is no issue related to this PR, replace this text with your example stock synthesis input.
```
-->
=> increase have_data storage to 150.

.github/workflows/build-ss3.yml
The macos-12 build using the admb docker image started failing after an update to the macos-12 github action runner. The macos-13 runner was also failing to build ss3 with the admb docker image. The workflow has been updated to use the macos-13 runner and build admb from source for that runner and then build ss3 rather than using the admb docker image.
See the [successful build](https://github.com/e-perl-NOAA/github-actions-test/actions/runs/10947197746) in my repo with the workflow.
None.
=> Update build-ss3.yml with admb build from source for macos-13

SS_versioninfo_330safe.tpl
Update the admb version in the versioninfo file.
None.
=> Update admb version to 13.2

SS_expval.tpl, SS_write_ssnew.tpl
The manual described the Q power feature incorrectly.  Here the correct description is added to the write_ssnew.  
There is no associated issue.
[x] No test files are required for this pull request. 
none
```
#_Q_setup for fleets with cpue or survey or deviation data
#_1:  fleet number
#_2:  link type: 1=simple q; 2=mirror; 3=power (+1 parm); 4=mirror with scale (+1p); 5=offset (+1p); 6=offset & power (+2p)
#_     where power is applied as y = q * x ^ (1 + power); so a power value of 0 has null effect
#_     and with the offset included it is y = q * (x + offset) ^ (1 + power)
#_3:  extra input for link, i.e. mirror fleet# or dev index number
#_4:  0/1 to select extra sd parameter
#_5:  0/1 for biasadj or not
#_6:  0/1 to float
```
=> adjust description of Q power

.github/workflows/run-ss3-bootstrap.yml, .github/workflows/test-r4ss-with-ss3.yml, SS_versioninfo_330opt.tpl, SS_versioninfo_330safe.tpl
=> Update version info user support and user info sites

SS_write_ssnew.tpl
add code to allow 2dar output to control.ssnew when sigma_amax<0
* Resolves issue #678
verified that revised code produces the expected line in control.ssnew
<-- - [x] Test files are in the issue. -->
None
@EJDick-NOAA
=> fix 2dar control_ssnew
